### ISSUE TITLE
Class Code Review

### ISSUE THREAD

**Issue by JDMartinez1531** [KEDuran/Portfolio-React#28]
I tried to go through your code in an order that made sense, If it seems like I'm skipping around, just know it's because I didn't see anything (to my knowledge) that was worth mentioning. All in all, this was very difficult for me because it looks so nice. I'm not trying to knit pick, just really struggling to find something to review.

**Projects**
- [x] Your project card component is beautiful and looks very reusable, but maybe you could use some conditional rendering to pass the props to your cards from an array. That way, you would't have to hard code additional project cards as your portfolio grows.

- [x] Responsiveness: From screen width 1200 - 992, I noticed the left column extends a little farther than the right. They even out until width 767. The images got really blurry and squished together for me at this point, maybe try reformatting the images or having the project section switch to a single column at a wider break point. Otherwise, everything is nice and responsive, very easy to see what's going on here,

**Fun Facts**

- [x] Looks Beautiful, no responsiveness issues that I can see. Only thing would again maybe you could reduce the amount of code by conditionally rendering those fun fact cards.

**Contact** 

https://github.com/KEDuran/Portfolio-React/blob/731adcd2264b11f9575c86038ffffde850f2ea97/src/pages/Contact/index.js#L26-L33
- [x] First of all, let me say what an incredibly elegant way to handle this form issue.

- [x] The whole page is responsive and styled well for the most part. The only thing that stands out to me is the width of your form input group.prepend labels and submit button not aligning. Maybe setting them to the same width would look a little cleaner.

- [ ]  (KD Note - Future Development) Get it working. I took the easy way out and used [Formspree.io](https://formspree.io)

**Comment by KEDuran** [comment]
@JDMartinez1531 Thank you very much for the code review!! I really appreciate your feedback and incorporated all the checked items listed in your issues message. 

Overall, I refactored my portfolio code to be much more dry and utilize the intent of React.js. I did not enable message sending at this time. I will add the message sending item as a `nice to have` for future development.
